after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

[workspace-to-monitor-force-assignment]
S = "secondary"

[mode.main.binding]
ctrl-alt-cmd-shift-t = "layout tiles horizontal vertical"
ctrl-alt-cmd-shift-a = "layout accordion horizontal vertical"
ctrl-alt-cmd-shift-m = "focus left"
ctrl-alt-cmd-shift-n = "focus down"
ctrl-alt-cmd-shift-e = "focus up"
ctrl-alt-cmd-shift-i = "focus right"
ctrl-alt-shift-m = "move left"
ctrl-alt-shift-n = "move down"
ctrl-alt-shift-e = "move up"
ctrl-alt-shift-i = "move right"
ctrl-alt-cmd-shift-minus = "resize smart -50"
ctrl-alt-cmd-shift-equal = "resize smart +50"
ctrl-alt-cmd-shift-l = "workspace 0"
ctrl-alt-cmd-shift-u = "workspace 1"
ctrl-alt-cmd-shift-y = "workspace 2"
ctrl-alt-cmd-shift-semicolon = "workspace 3"
ctrl-alt-cmd-shift-p = "workspace 4"
ctrl-alt-cmd-shift-f = "workspace 5"
ctrl-alt-cmd-shift-w = "workspace 6"
ctrl-alt-cmd-shift-q = "workspace 7"
ctrl-alt-cmd-shift-j = "workspace S"
ctrl-alt-shift-l = "move-node-to-workspace 0"
ctrl-alt-shift-u = "move-node-to-workspace 1"
ctrl-alt-shift-y = "move-node-to-workspace 2"
ctrl-alt-shift-semicolon = "move-node-to-workspace 3"
ctrl-alt-shift-p = "move-node-to-workspace 4"
ctrl-alt-shift-f = "move-node-to-workspace 5"
ctrl-alt-shift-w = "move-node-to-workspace 6"
ctrl-alt-shift-q = "move-node-to-workspace 7"
ctrl-alt-shift-j = "move-node-to-workspace S"
ctrl-alt-cmd-shift-tab = "workspace-back-and-forth"
ctrl-alt-cmd-shift-s = "mode service"
ctrl-alt-cmd-shift-r = "mode resize"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"]
f = ["layout floating tiling", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
m = ["join-with left", "mode main"]
n = ["join-with down", "mode main"]
e = ["join-with up", "mode main"]
i = ["join-with right", "mode main"]

[mode.resize.binding]
esc = ["reload-config", "mode main"]
minus = ["resize smart -50"]
equal = ["resize smart +50"]

