after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

[workspace-to-monitor-force-assignment]
S = "secondary"

[mode.main.binding]
alt-slash = "layout tiles horizontal vertical"
alt-comma = "layout accordion horizontal vertical"
alt-m = "focus left"
alt-n = "focus down"
alt-e = "focus up"
alt-i = "focus right"
alt-shift-m = "move left"
alt-shift-n = "move down"
alt-shift-e = "move up"
alt-shift-i = "move right"
alt-minus = "resize smart -50"
alt-equal = "resize smart +50"
alt-0 = "workspace 0"
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-s = "workspace S"
alt-shift-0 = "move-node-to-workspace 0"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-s = "move-node-to-workspace S"
alt-tab = "workspace-back-and-forth"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-semicolon = "mode service"
alt-shift-r = "mode resize"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"] # reset layout
f = ["layout floating tiling", "mode main"] # Toggle between floating and tiling layout
backspace = ["close-all-windows-but-current", "mode main"]
alt-shift-m = ["join-with left", "mode main"]
alt-shift-n = ["join-with down", "mode main"]
alt-shift-e = ["join-with up", "mode main"]
alt-shift-i = ["join-with right", "mode main"]

[mode.resize.binding]
esc = "mode main"
minus = "resize smart -50"
equal = "resize smart +50"

